add custom BACKUP_FILE for create and restore script

diff --git a/create b/create
--- a/create
+++ b/create
@@ -2,8 +2,18 @@
 
 set -eu
 
-BACKUP_FILE=/backup/mediawiki-backup.tar
-rm -f $BACKUP_FILE
+BACKUP_FILE=${BACKUP_FILE:-"/backup/mediawiki-backup.tar"}
+
+if [[ -z "$BACKUP_FILE" ]]; then
+    echo "Error: BACKUP_FILE is not set."
+    exit 1
+fi
+
+if [[ "$BACKUP_FILE" == "/backup/mediawiki-backup.tar" ]]; then
+    echo "Removing old backup file: $BACKUP_FILE"
+    rm -f "$BACKUP_FILE"
+fi
+
 
 TMP_FOLDER=`mktemp -d`
 cd $TMP_FOLDER
